name: Automate Release Versioning

on:
  push:
    branches:
      - main # Trigger when changes are pushed to main (e.g., after develop is merged)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push commits and tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for standard-version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use the Node.js version your project uses

      - name: Install dependencies
        run: npm install

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run standard-version
        id: standard_version
        run: npx standard-version

      - name: Push changes and tag
        run: |
          git push --follow-tags origin main
