name: Vault CI (User)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Markdownlint CLI
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint (Main Vault)
        run: markdownlint '**/*.md' --ignore '00 - Inbox/**/*.md' --config .markdownlint.json

      - name: Run Markdownlint (Docs)
        run: cd docs && markdownlint '**/*.md'

      - name: Run Markdownlint (Templates)
        run: cd "90 - Templates" && markdownlint '**/*.md'
