# .github/workflows/initialize.yml
name: 🎉 Inicializa o Vault no Primeiro Push

on:
  push:
    branches:
      - main

jobs:
  initialize-and-self-destruct:
    runs-on: ubuntu-latest
    # Apenas executa se for um push para a branch 'main' E
    # se o repositório NÃO for o repositório de template original 'aretw0/vault-seed'.
    if: github.ref == 'refs/heads/main' && github.repository != 'aretw0/vault-seed'

    steps:
      - name: 🛎️ Clona o Repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Configura o Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🧹 Reseta os Arquivos do Projeto
        run: |
          echo "🔥 Resetando CHANGELOG.md"
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "Todas as mudanças notáveis neste projeto serão documentadas neste arquivo." >> CHANGELOG.md
          
          echo "🔥 Resetando VERSION para 0.0.1"
          echo "0.0.1" > VERSION

      - name: ✨ Prepara Documentação Inicial
        run: |
          echo "🔥 Copiando e personalizando README.md"
          cp README.template.md README.md
          sed -i "s/{{REPO_NAME}}/${{ github.event.repository.name }}/g" README.md

          echo "🔥 Copiando CONTRIBUTING.md"
          cp CONTRIBUTING.template.md CONTRIBUTING.md

          echo "🗑️ Removendo arquivos de template"
          rm README.template.md CONTRIBUTING.template.md

      - name: ✨ Configura Workflow de Release para Novo Cofre
        run: |
          echo "🔥 Configurando o workflow de release para o novo cofre."
          # Substitui os comentários iniciais para refletir que o workflow está adormecido
          sed -i '1,8c\# .github/workflows/release.yml\nname: Publicar Release\n\n\# Este workflow está configurado para ser executado manualmente ou por um push de tag.\n\# Ele não será executado automaticamente em cada push para a branch principal.\n\# Para ativá-lo, você pode:\n\# 1. Descomentar a seção 'on: push: tags:' abaixo.\n\# 2. Executá-lo manualmente através da aba 'Actions' no GitHub.' .github/workflows/release.yml

          # Comenta as linhas que ativam o workflow de release por push de tag
          sed -i '/^on:/a\  # push:\n  #   tags:\n  #     - \'v*\' \# Executa quando uma nova tag (ex: v1.0.0) é criada e enviada.\n' .github/workflows/release.yml
          sed -i '/^on:/d' .github/workflows/release.yml \# Remove the original 'on:' line

      - name: 🗑️ Auto-destrói e Commita
        run: |
          git add CHANGELOG.md VERSION README.md CONTRIBUTING.md .github/workflows/release.yml \# Add release.yml to staged files
          
          echo "💥 Apagando o arquivo de workflow para garantir que ele rode apenas uma vez."
          git rm --ignore-unmatch .github/workflows/initialize.yml
          
          if ! git diff-index --quiet --cached HEAD; then
            git commit -m "chore(project): 🎉 inicializa o vault a partir do template"
            git push
          else
            echo "✅ Vault já inicializado. Nenhum novo commit necessário."
          fi