# .github/workflows/initialize.yml
name: 🎉 Inicializa o Vault no Primeiro Push

on:
  push:
    branches:
      - main

jobs:
  initialize-and-self-destruct:
    runs-on: ubuntu-latest
    # Apenas executa se for um push para a branch 'main' E
    # se o repositório NÃO for o repositório de template original 'aretw0/vault-seed'.
    if: github.ref == 'refs/heads/main' && github.repository != 'aretw0/vault-seed'

    steps:
      - name: 🛎️ Clona o Repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⚙️ Configura o Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🧹 Reseta os Arquivos do Projeto
        run: |
          echo "🔥 Resetando CHANGELOG.md"
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "Todas as mudanças notáveis neste projeto serão documentadas neste arquivo." >> CHANGELOG.md
          
          echo "🔥 Resetando VERSION para 0.0.1"
          echo "0.0.1" > VERSION

      - name: ✨ Prepara Documentação Inicial
        run: |
          echo "🔥 Copiando e personalizando README.md"
          cp README.template.md README.md
          sed -i "s/{{REPO_NAME}}/${{ github.event.repository.name }}/g" README.md

          echo "🔥 Copiando CONTRIBUTING.md"
          cp CONTRIBUTING.template.md CONTRIBUTING.md

          echo "🗑️ Removendo arquivos de template"
          rm README.template.md CONTRIBUTING.template.md

      - name: 🗑️ Auto-destrói e Commita
        run: |
          git rm --ignore-unmatch .github/workflows/initialize.yml
          echo "🗑️ Removendo o workflow de CI template para simplificar o setup inicial."
          rm -f .github/workflows/template-ci.yml
          echo "🗑️ Removendo templates de Pull Request técnicos para simplificar o setup inicial."
          rm -f .github/PULL_REQUEST_TEMPLATE/chore-maintenance.md
          rm -f .github/PULL_REQUEST_TEMPLATE/feat-technical-enhancement.md
          rm -f .github/PULL_REQUEST_TEMPLATE/fix-technical.md
          rm -f .github/PULL_REQUEST_TEMPLATE/refactor-knowledge-note.md
          echo "🗑️ Removendo o workflow de automação de versionamento para simplificar o setup inicial."
          rm -f .github/workflows/automate-versioning.yml
          
          # Adiciona todos os arquivos que foram removidos ou modificados para o stage
          git add CHANGELOG.md VERSION README.md CONTRIBUTING.md \
              .github/workflows/template-ci.yml \
              .github/workflows/automate-versioning.yml \
              .github/PULL_REQUEST_TEMPLATE/chore-maintenance.md \
              .github/PULL_REQUEST_TEMPLATE/feat-technical-enhancement.md \
              .github/PULL_REQUEST_TEMPLATE/fix-technical.md \
              .github/PULL_REQUEST_TEMPLATE/refactor-knowledge-note.md
          
          if ! git diff-index --quiet --cached HEAD; then
            git commit -m "chore(project): 🎉 inicializa o vault a partir do template"
            git push
          else
            echo "✅ Vault já inicializado. Nenhum novo commit necessário."
          fi
