# .github/workflows/release.yml
name: Publicar Release

# Este workflow é executado automaticamente quando uma nova tag (ex: v1.0.0) é criada e enviada para o repositório.
# Ele automatiza a criação de releases no GitHub, extraindo as notas do CHANGELOG.md.
# Você também pode executá-lo manualmente através da aba 'Actions' no GitHub.

on:
  push:
    tags:
      - 'v*' # Executa quando uma nova tag (ex: v1.0.0) é criada e enviada.
  workflow_dispatch: # Permite execução manual através da interface do GitHub Actions

permissions:
  contents: write # Permite que o GITHUB_TOKEN crie e edite releases e outros conteúdos do repositório.

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para que standard-version possa analisar o histórico completo

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a versão do Node.js que seu projeto utiliza

      - name: 📦 Instalar Dependências
        run: npm install # Instala as dependências do package.json, incluindo standard-version

      - name: 🛡️ Verificar Commits para Changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "::warning::Nenhuma tag anterior encontrada. Verificando todos os commits."
            COMMITS_SINCE_LAST_TAG=$(git log --pretty=format:"%s")
          else
            echo "::debug::Última tag encontrada: $LAST_TAG"
            COMMITS_SINCE_LAST_TAG=$(git log $LAST_TAG..HEAD --pretty=format:"%s")
          fi

          echo "::debug::Commits desde a última tag ou início do histórico:"
          echo "$COMMITS_SINCE_LAST_TAG"

          # Verifica se há commits que geram changelog (feat, fix, refactor, ou BREAKING CHANGE)
          # Usamos grep -E para regex estendida e -q para modo silencioso (apenas status de saída)
          if echo "$COMMITS_SINCE_LAST_TAG" | grep -Eq "^(feat|fix|refactor):|BREAKING CHANGE:"; then
            echo "::notice::Commits relevantes para o changelog encontrados. Prosseguindo com a release."
          else
            echo "::error::Nenhum commit do tipo 'feat', 'fix', 'refactor' ou 'BREAKING CHANGE' encontrado desde a última release."
            echo "::error::Não será possível gerar uma release com conteúdo vazio no changelog."
            echo "::error::Por favor, adicione um commit relevante e tente novamente."
            exit 1
          fi

      - name: 📝 Obter Notas de Release
        id: get_release_notes
        run: |
          # Extrai as notas de release do CHANGELOG.md para a tag atual
          VERSION_TAG=$(echo ${{ github.ref_name }} | sed 's/v//')
          RELEASE_NOTES=$(node scripts/get_release_notes.js "$VERSION_TAG")

          # Garante que as notas não estejam vazias
          if [ -z "$RELEASE_NOTES" ]; then
            echo "::error::Não foi possível extrair as notas de release para a versão ${VERSION_TAG} do CHANGELOG.md."
            exit 1
          fi

          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 🚀 Criar GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ steps.get_release_notes.outputs.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN é fornecido automaticamente pelo GitHub
