name: 🚀 Automação de Release e Versionamento

on:
  push:
    branches:
      - main # Este workflow é acionado quando algo é mesclado na branch 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para criar tags e releases
      issues: write # Permissão para criar GitHub releases
      pull-requests: write # Permissão para atualizar pull requests (se necessário pelos plugins)

    steps:
      - name: 🛎️ Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para analisar o histórico completo de commits

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a versão do Node.js que seu projeto utiliza

      - name: 📦 Instalar Dependências
        run: npm install # Instala as dependências do projeto, incluindo o semantic-release

      - name: 👤 Configurar Usuário Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🚀 Executar Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token fornecido pelo GitHub Actions
        run: npx semantic-release
