name: Sync Develop with Main

on:
  push:
    branches:
      - main

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main into develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --no-rebase

      - name: Push changes to develop
        run: |
          git push origin develop
